os: linux
dist: focal
language: generic
services:
  - docker

jobs:
  include:
    - stage: Building and running UD-Viz container
      script:
        - docker build  -t vcity:geovolume-server Context
        - docker run --rm --detach -t vcity:geovolume-server
        - travis_wait 2
        - docker stop $(docker ps -a -q --filter ancestor=vcity:geovolume-server --format="{{.ID}}")
    - stage: "Markdown link checks"
      language: node_js
      node_js: 15
      before_install:
        - npm --version
      install:
        - npm install --global remark-cli remark-validate-links
      env:
        - FAILURE_THRESHOLD=0
      script:
        - remark -u validate-links .
        - export warnings=`remark -u validate-links . 2>&1 | grep warning | grep "Link to unknown" | wc -l` &&
          if [ $warnings -gt $FAILURE_THRESHOLD ]; then
          exit 1;
          fi
